### ISSUE TITLE
Does this work on modded mobs too?

### ISSUE THREAD

**Issue by VeggeieDude** [Roundaround/mc-fabric-babies-forever#1]
Hello! Does this mod stop modded mobs from growing up too?

**Comment by VeggeieDude** [comment]
Oh also is this serverside only? Sorry for all the questions lol

**Comment by Roundaround** [comment]
It should work on any mob that extends the vanilla "Passive" mob, so while I would like to say yes, it's not 100% guaranteed other mods will implement it that way.

And yes, server-side (and single player) only!
